package com.decisioncopilot.service;

import com.decisioncopilot.dto.ProductData;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * UPDATED: Validates product segment, delegates feature details to Gemini LLM
 * No more hardcoded features - all details from AI
 */
@Service
public class ProductDataServiceImpl implements ProductDataService {

    private static final Set<String> VALID_KEYWORDS = Set.of(
        "iphone", "galaxy", "pixel", "poco", "redmi", "xiaomi", "oneplus", "realme", "oppo", "vivo",
        "nothing", "motorola", "asus", "dell", "hp", "lenovo",
        "macbook", "laptop", "thinkpad", "ideapad", "chromebook", "ultrabook", "vivobook",
        "headphone", "earbuds", "airpods", "wh-1000", "speaker", "soundbar", "anc",
        "desk", "chair", "mixer", "induction", "vacuum", "book", "kindle", "shirt", "pants",
        "watch", "smartwatch", "band", "bracelet", "monitor", "keyboard", "mouse", "camera"
    );

    @Override
    public ProductData fetchProductData(String input, String category) {
        String trimmedInput = input.trim();
        
        // Validate actual product name
        if (!isValidProductQuery(trimmedInput)) {
            throw new IllegalArgumentException(
                "Invalid product input: '" + trimmedInput + "'. Please provide an actual product name or model " +
                "(e.g., 'iPhone 15', 'Samsung Galaxy S24', 'Sony WH-1000XM5', 'AirPods Pro')"
            );
        }

        int hash = Math.abs(input.hashCode());
        String cat = category != null ? category.trim() : "general";
        String lower = input.toLowerCase(Locale.ROOT);

        // Validate segment exists (structure validation only)
        Segment segment = inferSegment(lower, cat);

        // Generate minimal base data
        BigDecimal price = generatePrice(lower, cat, hash);
        BigDecimal rating = generateRating(hash);
        int reviewCount = generateReviewCount(hash);

        // Features and specs will be generated by Gemini LLM in background
        // Return empty for now - Gemini populates during decision processing
        String[] features = new String[0];
        String specSummary = "Product details being analyzed by AI...";

        return new ProductData(
            input,
            price,
            rating,
            reviewCount,
            cat,
            null,
            null,
            features,
            specSummary
        );
    }

    private boolean isValidProductQuery(String input) {
        if (input == null || input.isBlank() || input.length() < 3) {
            return false;
        }

        String lower = input.toLowerCase(Locale.ROOT);
        
        if (lower.startsWith("what is") || lower.startsWith("who is") || 
            lower.startsWith("how to") || lower.startsWith("tell me") ||
            lower.startsWith("can you") || lower.startsWith("do you") ||
            lower.startsWith("why") || lower.startsWith("when")) {
            return false;
        }

        if (lower.equals("phone") || lower.equals("laptop") || lower.equals("product") || 
            lower.equals("headphone") || lower.equals("speaker")) {
            return false;
        }

        boolean hasKeyword = VALID_KEYWORDS.stream().anyMatch(lower::contains);
        boolean looksLikeProductName = input.matches(".*[A-Z0-9].*") && input.length() > 3;

        return hasKeyword || looksLikeProductName;
    }

    private enum Segment {
        SMARTPHONE, LAPTOP, AUDIO, HOME, FITNESS, FASHION, BOOKS, GENERAL
    }

    private Segment inferSegment(String lower, String category) {
        if (matchesAudio(lower)) return Segment.AUDIO;
        if (matchesLaptop(lower)) return Segment.LAPTOP;
        if (matchesSmartphone(lower)) return Segment.SMARTPHONE;
        
        if ("fitness".equalsIgnoreCase(category)) return Segment.FITNESS;
        if ("fashion".equalsIgnoreCase(category)) return Segment.FASHION;
        if ("books".equalsIgnoreCase(category)) return Segment.BOOKS;
        if ("home".equalsIgnoreCase(category) || matches(lower, "desk", "chair", "mixer", "induction", "vacuum")) {
            return Segment.HOME;
        }
        
        return Segment.GENERAL;
    }

    private boolean matchesAudio(String lower) {
        return matches(lower, "headphone", "earbuds", "airpods", "wh-1000", "speaker", "soundbar", "anc");
    }

    private boolean matchesLaptop(String lower) {
        return matches(lower, "macbook", "thinkpad", "ideapad", "chromebook", "ultrabook", "vivobook", "laptop");
    }

    private boolean matchesSmartphone(String lower) {
        return matches(lower, "iphone", "galaxy", "pixel", "poco", "redmi", "xiaomi", "oneplus", "realme", "5g", "smartphone");
    }

    private static boolean matches(String lower, String... needles) {
        for (String n : needles) {
            if (lower.contains(n)) return true;
        }
        return false;
    }

    private BigDecimal generatePrice(String lower, String category, int hash) {
        if (lower.contains("iphone")) {
            return BigDecimal.valueOf(52_999 + (hash % 85_000)).setScale(0, RoundingMode.HALF_UP);
        }
        if (lower.contains("macbook")) {
            return BigDecimal.valueOf(89_999 + (hash % 120_000)).setScale(0, RoundingMode.HALF_UP);
        }
        if (lower.contains("airpods")) {
            return BigDecimal.valueOf(19_999 + (hash % 30_000)).setScale(0, RoundingMode.HALF_UP);
        }
        return BigDecimal.valueOf(15_000 + (hash % 50_000)).setScale(0, RoundingMode.HALF_UP);
    }

    private BigDecimal generateRating(int hash) {
        double rating = 2.6 + (hash % 24) / 10.0;
        return BigDecimal.valueOf(Math.min(5.0, rating)).setScale(2, RoundingMode.HALF_UP);
    }

    private int generateReviewCount(int hash) {
        return 48 + (hash % 12_000);
    }
}